import { LEGAL_EFFECTIVE_DATE } from "../shared/legal";

export const LEGAL_VERSION = LEGAL_EFFECTIVE_DATE;

export interface LegalSection {
  id: string;
  title: string;
  body: string;
}

export interface LegalDocument {
  eyebrow: string;
  pageTitle: string;
  title: string;
  summary: string;
  sections: LegalSection[];
}

const privacyEmail =
  '<a href="mailto:privacy@permissiongranted.app">privacy@permissiongranted.app</a>';
const supportEmail =
  '<a href="mailto:support@permissiongranted.app">support@permissiongranted.app</a>';

export const privacyNotice: LegalDocument = {
  eyebrow: "PRIVACY NOTICE",
  pageTitle: "Privacy Notice",
  title: "Your data, on the record.",
  summary:
    "This notice explains what Permission Granted collects, why it is used, who receives it, how long it is kept, and the choices available to senders and recipients.",
  sections: [
    {
      id: "controller",
      title: "1. Who is responsible",
      body: `<p><strong>Aryan Alipour, trading as Permission Granted</strong>, is the controller of the personal information described in this notice. Permission Granted is operated from England.</p>
        <p>Privacy questions and data-rights requests can be sent to ${privacyEmail}. General service questions can be sent to ${supportEmail}.</p>`,
    },
    {
      id: "scope",
      title: "2. Who and what this covers",
      body: `<p>This notice covers visitors to permissiongranted.app, people who create a request (“senders”), people named or emailed in a request (“recipients”), and people who submit an abuse report.</p>
        <p>The service is intended for adults aged 18 and over. Please do not use it to submit children’s information or special-category information such as health, biometric, political, religious, sexual-life, or trade-union information.</p>`,
    },
    {
      id: "data",
      title: "3. Information we process",
      body: `<div class="legal-table-wrap"><table class="legal-table">
          <thead><tr><th>Category</th><th>Examples</th><th>Source</th></tr></thead>
          <tbody>
            <tr><td>Request details</td><td>Sender and recipient names, request title, justification, status, decision, and timestamps</td><td>The sender; then the recipient when they decide</td></tr>
            <tr><td>Contact details</td><td>Sender and recipient email addresses</td><td>The sender</td></tr>
            <tr><td>Delivery and security data</td><td>Email delivery identifiers and errors, encrypted capability records, keyed rate-limit identifiers, and report details</td><td>Generated by the service or supplied by a reporter</td></tr>
            <tr><td>Network and device data</td><td>IP address, browser and device signals, request metadata, and anti-bot results</td><td>Collected automatically by Cloudflare when the site and Turnstile are used</td></tr>
          </tbody>
        </table></div>
        <p>We do not knowingly collect payment data. We do not sell personal information, use it for behavioural advertising, send marketing email, publish requests, or use email-open tracking pixels.</p>`,
    },
    {
      id: "purposes",
      title: "4. Why we use it and our lawful bases",
      body: `<div class="legal-table-wrap"><table class="legal-table">
          <thead><tr><th>Purpose</th><th>Lawful basis</th></tr></thead>
          <tbody>
            <tr><td>Create, store, verify, deliver, and manage a sender’s request</td><td>Performance of our contract with the sender</td></tr>
            <tr><td>Show the request to the recipient, record their voluntary response, and notify the sender</td><td>Our legitimate interests in delivering the one-off communication requested by the sender, with equal decision controls and no obligation to respond</td></tr>
            <tr><td>Apply rate limits, verify humans, secure capability links, prevent abuse, and protect email deliverability</td><td>Our legitimate interests in keeping the service, its users, and other recipients safe</td></tr>
            <tr><td>Receive reports, disable misuse, investigate incidents, and establish or defend legal claims</td><td>Our legitimate interests in preventing harm and enforcing the Terms; legal obligation where a law requires action</td></tr>
            <tr><td>Respond to rights requests and comply with regulators, courts, or law enforcement</td><td>Legal obligation</td></tr>
          </tbody>
        </table></div>
        <p>Providing the information is not a statutory requirement. The sender must provide the marked fields to create a request; without them, we cannot provide the service. A recipient never has to respond.</p>`,
    },
    {
      id: "recipient-notice",
      title: "5. If somebody else supplied your details",
      body: `<p>If you are a recipient, the sender supplied your name and email address and wrote the request content. We use those details only to deliver and administer that request, protect the service, and handle any response or report. The first request email links to this notice and identifies the sender.</p>
        <p>You can ignore, decline, or report the request. Reporting normally disables an undecided request and helps us investigate misuse.</p>`,
    },
    {
      id: "sharing",
      title: "6. Who receives information",
      body: `<p>We use <strong>Cloudflare, Inc. and its affiliates</strong> to provide web hosting and security, Workers, D1 database storage, Turnstile anti-bot checks, transactional email delivery, logs, and DNS. Cloudflare acts as our processor for customer content and also processes certain network-security data under its own notices.</p>
        <p>The sender sees the recipient’s decision and the details originally submitted. The recipient sees the sender’s name and request. We may disclose limited information to professional advisers, regulators, courts, or public authorities where reasonably necessary or legally required. We do not provide request data to advertisers or data brokers.</p>`,
    },
    {
      id: "transfers",
      title: "7. International transfers",
      body: `<p>Cloudflare operates a global network, so information may be processed outside the United Kingdom and European Economic Area. Where a restricted transfer occurs, Cloudflare’s Data Processing Addendum provides for recognised safeguards including the EU Standard Contractual Clauses and the UK International Data Transfer Addendum. Cloudflare may also rely on an applicable adequacy decision or Data Privacy Framework certification.</p>
        <p>To request information about the safeguards relevant to your data, contact ${privacyEmail}.</p>`,
    },
    {
      id: "retention",
      title: "8. How long information is kept",
      body: `<ul>
          <li><strong>Unverified, pending, failed, disabled, or unanswered requests:</strong> until the request expires, normally 30 days after creation.</li>
          <li><strong>Approved or declined requests:</strong> up to 90 days after the decision, so the sender can access the record and delivery failures can be resolved.</li>
          <li><strong>Reports and delivery records:</strong> deleted with their associated request.</li>
          <li><strong>Application logs:</strong> no more than 7 days. Our custom logs exclude names, email addresses, request text, and capability links.</li>
          <li><strong>Cloudflare recovery copies:</strong> deleted records may remain for a limited period in protected service backups before being overwritten.</li>
        </ul>
        <p>Copies delivered to a sender’s or recipient’s email provider are controlled by that person and their provider, not by Permission Granted.</p>`,
    },
    {
      id: "security",
      title: "9. Security",
      body: `<p>Email addresses and recoverable capability values are encrypted before storage. Lookup values are hashed or keyed. Private links are long, random, excluded from search engines, and served with no-store and no-referrer controls. Data is encrypted in transit, and Cloudflare D1 encrypts stored database objects.</p>
        <p>No internet service can promise absolute security. Please treat private links like passwords and contact ${supportEmail} if one may have been exposed.</p>`,
    },
    {
      id: "rights",
      title: "10. Your data-protection rights",
      body: `<p>Depending on the circumstances and lawful basis, you may ask us to access, correct, erase, or restrict your information; receive information you provided in a portable format; or object to processing based on legitimate interests. You may also complain to a supervisory authority.</p>
        <p>Email ${privacyEmail} with enough information for us to identify the relevant request. We may ask for proportionate proof of identity or control of an email address. We normally respond within one month and do not charge a fee unless a request is manifestly unfounded or excessive.</p>
        <aside class="legal-callout"><strong>Your right to object</strong><p>You can object at any time to our use of your information based on legitimate interests. Tell us which use you object to and why. We will stop unless we demonstrate compelling legitimate grounds or need the information for legal claims.</p></aside>`,
    },
    {
      id: "automation",
      title: "11. Automated checks",
      body: `<p>Cloudflare Turnstile automatically assesses browser and network signals to distinguish people from abusive automation. A failed check can prevent creation of a request, but it does not produce a legal or similarly significant decision about you. We do not use personal information for marketing profiles.</p>`,
    },
    {
      id: "complaints",
      title: "12. Questions and complaints",
      body: `<p>Please contact ${privacyEmail} first so we can try to resolve the issue.</p>
        <p>You can also complain to the <a href="https://ico.org.uk/make-a-complaint/" target="_blank" rel="noreferrer">Information Commissioner’s Office</a>: Wycliffe House, Water Lane, Wilmslow, Cheshire SK9 5AF; telephone 0303 123 1113. If EU GDPR applies to you, you may also contact the supervisory authority where you live or work.</p>`,
    },
    {
      id: "changes",
      title: "13. Changes to this notice",
      body: `<p>We will update this notice before using personal information for a materially different purpose. The effective date at the top shows the current version. Material changes may also be highlighted on the site or in a service email where appropriate.</p>`,
    },
  ],
};

export const termsOfService: LegalDocument = {
  eyebrow: "TERMS OF SERVICE",
  pageTitle: "Terms of Service",
  title: "The rules of engagement.",
  summary:
    "These Terms govern permissiongranted.app. They keep a playful request playful, make recipient choice non-negotiable, and define the limits of this unofficial service.",
  sections: [
    {
      id: "operator",
      title: "1. About these Terms",
      body: `<p>Permission Granted is operated by <strong>Aryan Alipour, trading as Permission Granted</strong>, from England (“Permission Granted”, “we”, “us”). Contact us at ${supportEmail}.</p>
        <p>By submitting a request, you confirm that you are at least 18 and agree to these Terms. A recipient does not agree to these Terms merely because somebody emails them; the recipient remains free to ignore, decline, or report the request.</p>`,
    },
    {
      id: "service",
      title: "2. What the service does",
      body: `<p>The service lets a sender draft a one-off playful request, verify their email address, and email the request to a named recipient. The recipient may approve, decline, ignore, or report it. We may notify the sender of an approval or decline and provide an unofficial record.</p>
        <p>Permission Granted is not a legal, employment, government, financial, relationship, or consent-management service. A result has no legal force and must not be treated as legally valid consent or permission.</p>`,
    },
    {
      id: "eligibility",
      title: "3. Eligibility and sender promises",
      body: `<p>You may submit a request only if you are 18 or over and the recipient knows you and can reasonably expect a one-off playful email from you. You confirm that the information you submit is accurate enough not to mislead, that you have a lawful reason to provide it, and that your use will not infringe another person’s rights.</p>
        <p>Do not submit passwords, financial information, identification numbers, confidential workplace material, children’s information, or special-category personal information.</p>`,
    },
    {
      id: "acceptable-use",
      title: "4. Acceptable use",
      body: `<p>You must not use the service to:</p>
        <ul>
          <li>harass, threaten, shame, stalk, coerce, discriminate against, or repeatedly contact anyone;</li>
          <li>impersonate a person, employer, government, platform, or other authority, or suggest an affiliation that does not exist;</li>
          <li>send fraud, scams, phishing, malware, unlawful promotions, bulk messages, or unsolicited marketing;</li>
          <li>publish or request unlawful, defamatory, invasive, sexually exploitative, hateful, or violent content;</li>
          <li>seek consent for sex, medical treatment, contracts, employment, finance, travel, safeguarding, or any other decision where valid consent or formal authorisation matters;</li>
          <li>probe, disrupt, overload, reverse engineer, or bypass the service or its security and rate limits; or</li>
          <li>use automated tools to create or act on requests without our written permission.</li>
        </ul>`,
    },
    {
      id: "recipient-control",
      title: "5. Recipient control and reports",
      body: `<p>Approve and Decline are presented as equal choices. Opening an email link does not itself record a decision. The recipient must confirm on the website. No response is required.</p>
        <p>Recipients can report an unexpected or harmful request from its private link or by emailing ${supportEmail}. We may disable requests, block delivery, preserve limited evidence, or cooperate with authorities where proportionate.</p>`,
    },
    {
      id: "content",
      title: "6. Your content",
      body: `<p>You retain any rights you have in text you submit. You give us a limited, worldwide, non-exclusive licence to host, encrypt, reproduce, format, email, and display that content only as necessary to operate, secure, and support the service and enforce these Terms. The licence ends when the content is deleted, except for limited protected backups or evidence lawfully retained.</p>
        <p>You are responsible for your content and the consequences of sending it. We do not routinely review requests before delivery.</p>`,
    },
    {
      id: "availability",
      title: "7. Availability and changes",
      body: `<p>The service is currently provided without charge. We may change, suspend, limit, or discontinue features, and we may impose reasonable usage limits. We do not promise uninterrupted operation or guaranteed email delivery because browsers, networks, and email providers are outside our control.</p>
        <p>If paid features are introduced, separate pricing and any consumer cancellation information will be shown before purchase.</p>`,
    },
    {
      id: "enforcement",
      title: "8. Suspension and termination",
      body: `<p>We may refuse, disable, or remove a request and restrict access where we reasonably believe these Terms were breached, a recipient may be harmed, delivery reputation is threatened, or action is legally required. We may do this without advance notice where notice would increase risk.</p>`,
    },
    {
      id: "intellectual-property",
      title: "9. Our rights",
      body: `<p>The Permission Granted name, visual design, software, templates, and service content belong to us or our licensors. Except as the law permits, you may not copy, sell, sublicense, or create a misleadingly similar service using them. You may link to public pages without suggesting endorsement.</p>`,
    },
    {
      id: "liability",
      title: "10. Responsibility and liability",
      body: `<p>Nothing in these Terms excludes liability that cannot lawfully be excluded, including liability for death or personal injury caused by negligence, fraud, or fraudulent misrepresentation, or your statutory consumer rights.</p>
        <p>Subject to that, the service is supplied for light-hearted, personal use and on an “as available” basis. We are not responsible for a sender’s content, a recipient’s decision, lost or filtered email, reliance on an unofficial record, or loss that was not reasonably foreseeable when you used the service.</p>
        <p>If you use the service for business purposes, we are not liable for loss of profit, business, revenue, opportunity, goodwill, or anticipated savings. We do not exclude responsibility where doing so would be unfair or unlawful.</p>`,
    },
    {
      id: "privacy",
      title: "11. Privacy and service email",
      body: `<p>Our <a href="/privacy" data-link>Privacy Notice</a> explains how personal information is used. Our <a href="/cookies" data-link>Cookie Notice</a> explains the strictly necessary security technology used on the site.</p>
        <p>Verification, request, decision, safety, and support emails are service communications, not marketing. We do not add promotional content to them.</p>`,
    },
    {
      id: "law",
      title: "12. Law and disputes",
      body: `<p>These Terms are governed by the law of England and Wales. If you are a consumer, you keep any mandatory protections of the country where you live and may bring proceedings in any court available to you under applicable consumer law. Otherwise, the courts of England and Wales have exclusive jurisdiction.</p>
        <p>Please contact ${supportEmail} first so we can try to resolve a concern informally.</p>`,
    },
    {
      id: "changes",
      title: "13. Changes to these Terms",
      body: `<p>We may update these Terms for legal, security, or service changes. The effective date identifies the version that applies. Material changes will be presented before a new request is submitted; changes do not retrospectively alter an already recorded recipient decision.</p>`,
    },
  ],
};

export const cookieNotice: LegalDocument = {
  eyebrow: "COOKIE NOTICE",
  pageTitle: "Cookie Notice",
  title: "Only the necessary crumbs.",
  summary:
    "Permission Granted does not use advertising cookies or behavioural analytics. The site uses only technology needed to deliver and protect the service.",
  sections: [
    {
      id: "overview",
      title: "1. Our approach",
      body: `<p>We do not set cookies for advertising, cross-site tracking, marketing profiles, or email-open tracking. We do not run third-party audience analytics on permissiongranted.app.</p>
        <p>Cloudflare provides the site’s network security and Turnstile anti-bot check. Those services process browser, device, and network signals and may use strictly necessary cookies or similar storage when required to distinguish people from abusive automation and maintain security.</p>`,
    },
    {
      id: "technology",
      title: "2. Technology that may be used",
      body: `<div class="legal-table-wrap"><table class="legal-table">
          <thead><tr><th>Provider</th><th>Technology and purpose</th><th>Duration</th></tr></thead>
          <tbody>
            <tr><td>Cloudflare Turnstile</td><td>A short-lived challenge token and browser/network signals used to verify that a request is created by a person rather than abusive automation</td><td>The token is single-use and normally expires after five minutes; related security data follows Cloudflare’s applicable retention</td></tr>
            <tr><td>Cloudflare network security</td><td>Strictly necessary security cookies such as <code>cf_clearance</code> may be used if a Cloudflare challenge or pre-clearance feature is applied</td><td>For the security period set by Cloudflare and no longer than necessary for the challenge</td></tr>
          </tbody>
        </table></div>
        <p>The application itself does not use browser local storage or set an account/session cookie.</p>`,
    },
    {
      id: "consent",
      title: "3. Why there is no cookie banner",
      body: `<p>UK PECR permits storage that is strictly necessary to provide a service requested by the user or to transmit communications. Because the current site uses only necessary security technology, we provide this notice but do not ask for cookie consent.</p>
        <p>If we introduce non-essential analytics, advertising, or personalisation technology, it will remain off until you make a clear choice. We will update this notice and add appropriate controls before doing so.</p>`,
    },
    {
      id: "controls",
      title: "4. Your controls",
      body: `<p>You can block or delete cookies using browser settings. Blocking necessary Cloudflare security technology may prevent the request form from working. Closing the site is always an option, and recipients can decide by ignoring the email rather than opening the website.</p>`,
    },
    {
      id: "contact",
      title: "5. Contact",
      body: `<p>Questions about cookies or similar technology can be sent to ${privacyEmail}. For more about personal information and your rights, read the <a href="/privacy" data-link>Privacy Notice</a>.</p>`,
    },
  ],
};
